name: py-mypy

on:
  workflow_dispatch: {}

jobs:
  py-mypy:
    name: py-mypy
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install mypy

    - run: mypy binary-search-typed.py
